In [2]:
happy=14
print(happy)

14

In [3]:
sad=17
happy=91
print(happy+sad)

108

In [4]:
total=sad+happy
print(total)

108

# GDP per capita

In [2]:
import pandas as pd

GDPcap = pd.read_excel (r'BCLDatabase_online_v2.4.xlsx', 
                    sheet_name="GDP per capita")
print (GDPcap)

     Year           AUS           AUT           BEL           CAN  \
0    1890   8773.621382   4831.877350   4593.012106   4520.862868
1    1891   9184.546914   4966.374691   4531.899209   4578.550947
2    1892   7863.803255   5044.792029   4577.673020   4506.534723
3    1893   7297.826136   5037.894633   4578.748374   4435.938377
4    1894   7411.350492   5283.105231   4579.134233   4600.855868
..    ...           ...           ...           ...           ...
125  2015  48508.512900  48980.412430  42816.558182  46778.741303
126  2016  48887.422466  49462.692531  43230.086097  46715.194906
127  2017  49484.241049  50336.741242  43883.747532  47624.230723
128  2018  49654.242225  51304.273698  44334.315101  47908.771527
129  2019  49782.269777  51917.172343  44733.827198  48013.528771

              CHE           CHL           DEU           DNK           ESP  \
0     8291.383494   2124.391866   5917.076199   4596.498656   4037.580800
1     7783.766212   2269.345735   5886.166375   4654.675889   4111.133323
2     8357.129983   2196.933739   5908.525376   4732.299809   4399.716802
3     8584.418396   2278.545375   6275.039868   4788.673088   4226.817397
4     8285.551678   2214.786453   6404.765138   4840.936454   4255.146961
..            ...           ...           ...           ...           ...
125  68522.939622  23702.054307  48499.863276  47156.338318  35211.387352
126  68946.372447  23790.252338  49182.789904  48308.541658  36248.133328
127  69535.095553  23732.363693  50274.277220  48976.080332  37208.955109
128  70923.320891  24328.848399  50758.979704  49899.223207  37917.305108
129  71077.001488  24296.257117  50901.536302  50850.806211  38438.540692

     ...           JPN           MEX           NLD           NOR  \
0    ...   1761.057407   2821.345843   6558.994970   4289.836699
1    ...   1664.465268   2895.986378   6363.917982   4296.841695
2    ...   1762.367542   2967.481445   6394.369498   4350.852099
3    ...   1754.824345   3036.641503   6387.011545   4440.119060
4    ...   1948.091228   3102.803181   6460.287510   4425.922025
..   ...           ...           ...           ...           ...
125  ...  41861.634988  18962.894159  50932.916578  70285.266101
126  ...  42128.668365  19281.411868  51772.961089  70415.335789
127  ...  43112.994753  19461.953933  52965.958367  71471.671013
128  ...  43340.086932  19655.003671  53900.773340  71917.044596
129  ...  43714.869206  19413.353831  54484.848124  72258.050163

              NZL           PRT           SWE           USA  Unnamed: 24  \
0     6504.728714   2309.683456   3085.893906   4705.821446          NaN
1     6583.929639   2251.451453   3024.271294   4756.665752          NaN
2     6606.464966   2225.942144   3180.946326   4869.744336          NaN
3     6761.677954   2254.534641   3313.243962   4752.790766          NaN
4     6765.176564   2209.554461   3339.062021   4512.620118          NaN
..            ...           ...           ...           ...          ...
125  38184.745027  28768.809574  46545.596649  56881.783736          NaN
126  38800.971454  29442.524285  46916.167695  57442.127619          NaN
127  39509.115972  30549.297543  47476.885134  58412.316002          NaN
128  40230.478032  31405.196652  47843.680842  59849.189027          NaN
129  40468.547404  32130.192538  47896.429343  60853.531036          NaN

        Euro Area
0     4563.542476
1     4557.822128
2     4625.906783
3     4699.298939
4     4851.226784
..            ...
125  41683.515783
126  42342.998945
127  43336.063146
128  44017.156614
129  44462.273827

[130 rows x 26 columns]

In [3]:
import pandas as pd

GDPcap = pd.read_csv (r'BCL_GDP.csv')
print (GDPcap)

     Year     AUS     AUT     BEL     CAN     CHE     CHL     DEU     DNK  \
0    1890   8,774   4,832   4,593   4,521   8,291   2,124   5,917   4,596
1    1891   9,185   4,966   4,532   4,579   7,784   2,269   5,886   4,655
2    1892   7,864   5,045   4,578   4,507   8,357   2,197   5,909   4,732
3    1893   7,298   5,038   4,579   4,436   8,584   2,279   6,275   4,789
4    1894   7,411   5,283   4,579   4,601   8,286   2,215   6,405   4,841
..    ...     ...     ...     ...     ...     ...     ...     ...     ...
125  2015  48,509  48,980  42,817  46,779  68,523  23,702  48,500  47,156
126  2016  48,887  49,463  43,230  46,715  68,946  23,790  49,183  48,309
127  2017  49,484  50,337  43,884  47,624  69,535  23,732  50,274  48,976
128  2018  49,654  51,304  44,334  47,909  70,923  24,329  50,759  49,899
129  2019  49,782  51,917  44,734  48,014  71,077  24,296  50,902  50,851

        ESP  ...     JPN     MEX     NLD     NOR     NZL     PRT     SWE  \
0     4,038  ...   1,761   2,821   6,559   4,290   6,505   2,310   3,086
1     4,111  ...   1,664   2,896   6,364   4,297   6,584   2,251   3,024
2     4,400  ...   1,762   2,967   6,394   4,351   6,606   2,226   3,181
3     4,227  ...   1,755   3,037   6,387   4,440   6,762   2,255   3,313
4     4,255  ...   1,948   3,103   6,460   4,426   6,765   2,210   3,339
..      ...  ...     ...     ...     ...     ...     ...     ...     ...
125  35,211  ...  41,862  18,963  50,933  70,285  38,185  28,769  46,546
126  36,248  ...  42,129  19,281  51,773  70,415  38,801  29,443  46,916
127  37,209  ...  43,113  19,462  52,966  71,472  39,509  30,549  47,477
128  37,917  ...  43,340  19,655  53,901  71,917  40,230  31,405  47,844
129  38,439  ...  43,715  19,413  54,485  72,258  40,469  32,130  47,896

        USA Unnamed: 24 Euro Area
0     4,706         NaN     4,564
1     4,757         NaN     4,558
2     4,870         NaN     4,626
3     4,753         NaN     4,699
4     4,513         NaN     4,851
..      ...         ...       ...
125  56,882         NaN    41,684
126  57,442         NaN    42,343
127  58,412         NaN    43,336
128  59,849         NaN    44,017
129  60,854         NaN    44,462

[130 rows x 26 columns]